"""Add UniqueConstraint to likes

Revision ID: 3001716b9785
Revises: 40f2527aa2fc
Create Date: 2026-03-01 20:13:05.467938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3001716b9785'
down_revision: Union[str, Sequence[str], None] = '40f2527aa2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_like_user_prompt', ['user_session', 'prompt_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_like_user_prompt', type_='unique')
    # ### end Alembic commands ###
