"""Add indexes to prompts table

Revision ID: 40f2527aa2fc
Revises: a91996c936d6
Create Date: 2026-03-01 20:09:49.881522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f2527aa2fc'
down_revision: Union[str, Sequence[str], None] = 'a91996c936d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_prompts_category'), 'prompts', ['category'], unique=False)
    op.create_index(op.f('ix_prompts_elo_rating'), 'prompts', ['elo_rating'], unique=False)
    op.create_index(op.f('ix_prompts_likes_count'), 'prompts', ['likes_count'], unique=False)
    op.create_index(op.f('ix_prompts_media_type'), 'prompts', ['media_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_media_type'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_likes_count'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_elo_rating'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_category'), table_name='prompts')
    # ### end Alembic commands ###
