"""add moderation status and other fields

Revision ID: c75ac982ce2a
Revises: 3001716b9785
Create Date: 2026-03-06 11:45:33.118485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c75ac982ce2a'
down_revision: Union[str, Sequence[str], None] = '3001716b9785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts') as batch_op:
        batch_op.add_column(sa.Column('moderation_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='approved'))
        batch_op.add_column(sa.Column('moderated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('moderated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ai_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('vk_post_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('telegram_message_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('prompts') as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_moderation_status'), ['moderation_status'], unique=False)
        batch_op.create_foreign_key('fk_prompts_moderated_by_users', 'users', ['moderated_by'], ['id'])

    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('vk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='local'))
        batch_op.add_column(sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('users') as batch_op:
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_vk_id'), ['vk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_vk_id'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('vk_id')
        batch_op.drop_column('google_id')

    with op.batch_alter_table('prompts') as batch_op:
        batch_op.drop_constraint('fk_prompts_moderated_by_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prompts_moderation_status'))
        batch_op.drop_column('telegram_message_url')
        batch_op.drop_column('vk_post_url')
        batch_op.drop_column('file_path')
        batch_op.drop_column('ai_model')
        batch_op.drop_column('moderated_at')
        batch_op.drop_column('moderated_by')
        batch_op.drop_column('moderation_status')
    # ### end Alembic commands ###
